version: '3'

services:
  api:
    build:
      context: /backend
    container_name: api
    ports:
      - 5000:5000
    depends_on:
      - db
  
  db:
    image: mysql
    restart: unless-stopped
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=root
      - MYSQL_PASSWORD=root
      - MYSQL_DATABASE=app
    volumes:
      - mysql_data:/var/lib/mysql
  
  # frontend:
  #   build: 
  #     context: /frontend
  #   ports:
  #     - 8080:80

volumes:
  mysql_data: 